/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import classes.Cartao;
import classes.Conta;
import classes.Usuario;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wally
 */
public class IUCartao extends javax.swing.JDialog {

    IUPrincipal principal = new IUPrincipal();
    ArrayList<Conta> contas;
    Usuario usuario = principal.getUsuarioCorrente();
    
    public IUCartao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        contas = usuario.getContas();
        
        comboBoxConta.removeAllItems();
        
        for( Conta c: contas )
            comboBoxConta.addItem(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textBandeira = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNumCartao = new javax.swing.JTextField();
        textVencimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textLimite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        registrar_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboBoxConta = new javax.swing.JComboBox();
        passwordSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("BANDEIRA");

        jLabel2.setText("NUM. CARTÃO");

        jLabel3.setText("VENCIMENTO");

        jLabel4.setText("LIMITE");

        jLabel5.setText("SENHA");

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/delete.png"))); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        registrar_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/registrar.png"))); // NOI18N
        registrar_Button.setText("Registrar");
        registrar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("VINCULAR CONTA");

        comboBoxConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBandeira)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNumCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textLimite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textVencimento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordSenha))
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registrar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(107, 107, 107)
                        .addComponent(buttonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textBandeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNumCartao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textLimite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        textBandeira.setText("");
        textNumCartao.setText("");
        textLimite.setText("");
        textVencimento.setText("");
        passwordSenha.setText("");
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void registrar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_ButtonActionPerformed
        String bandeira, numCartao, senha;
        float limite = 0.0f;
        Conta conta;
        Date vencimento = null;
        
        numCartao = textNumCartao.getText();
        bandeira = textBandeira.getText();
        senha = new String ( passwordSenha.getPassword() );
        conta = (Conta) comboBoxConta.getSelectedItem();
        
        if ( !textLimite.getText().equals("") )
            limite = Float.parseFloat( textLimite.getText() );
        
        try {
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            vencimento = (Date) formatter.parse( textVencimento.getText() );
        } catch (ParseException ex) {
            Logger.getLogger(IUCartao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if ( !numCartao.equals("") && !bandeira.equals("") && vencimento != null && !senha.equals("") && !textLimite.getText().equals("") )
            if( principal.controlador.buscarCartao(usuario, conta, numCartao) != null )
                JOptionPane.showMessageDialog(null, "Cartão de Crédito já existe !", "Erro", JOptionPane.ERROR_MESSAGE);

            else {
                principal.controlador.registrarCartao( usuario, conta, 
                        new Cartao( bandeira, numCartao, senha, vencimento, limite  ) );
                
                principal.controlador.armazenarUsuarios();
                JOptionPane.showMessageDialog(null, "Cartão de Crédito registrado com sucesso !", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }

        else
            JOptionPane.showMessageDialog(null, "Preencha Todos os campos !", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_registrar_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCartao dialog = new IUCartao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JComboBox comboBoxConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passwordSenha;
    private javax.swing.JButton registrar_Button;
    private javax.swing.JTextField textBandeira;
    private javax.swing.JTextField textLimite;
    private javax.swing.JTextField textNumCartao;
    private javax.swing.JTextField textVencimento;
    // End of variables declaration//GEN-END:variables
}
