/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import classes.Conta;
import classes.Controlador;
import classes.Gastos;
import classes.PieChart;
import classes.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Victor
 */
public class IUPrincipal extends javax.swing.JFrame {
    
    public static Controlador controlador = new Controlador();
    public static Usuario usuarioCorrente;
    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
        
        buttonGastos.setToolTipText("Gastos");
        buttonAlterarUsuario.setToolTipText("Alterar Usuário");
        buttonCartaoCredito.setToolTipText("Cartão de Crédito");
        buttonContaCorrente.setToolTipText("Conta Corrente");
        buttonInvestimento.setToolTipText("Investimento");
        buttonRenda.setToolTipText("Renda");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraLateral = new javax.swing.JPanel();
        buttonGastos = new javax.swing.JButton();
        buttonContaCorrente = new javax.swing.JButton();
        buttonInvestimento = new javax.swing.JButton();
        buttonAlterarUsuario = new javax.swing.JButton();
        buttonCartaoCredito = new javax.swing.JButton();
        buttonRenda = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableGastos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        buttonGraficoPeriodoTempo = new javax.swing.JButton();
        buttonGraficoConta = new javax.swing.JButton();
        buttonGraficoCartao = new javax.swing.JButton();
        buttonRelatorioPeriodoTempo = new javax.swing.JButton();
        buttonRelatorioConta = new javax.swing.JButton();
        buttonRelatorioCartao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelTotalGasto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelSaldoTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelTotalLimite = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        registrarGasto_MenuItem = new javax.swing.JMenuItem();
        contaMenuItem = new javax.swing.JMenuItem();
        cartaoMenuItem = new javax.swing.JMenuItem();
        registrarRenda_MenuItem = new javax.swing.JMenuItem();
        investimentoMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemCartao = new javax.swing.JMenuItem();
        menuItemConta = new javax.swing.JMenuItem();
        menuItemRenda = new javax.swing.JMenuItem();
        menuItemInvestimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraLateral.setBackground(new java.awt.Color(181, 181, 181));

        buttonGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/gastos1.png"))); // NOI18N
        buttonGastos.setToolTipText("Registrar Gasto");
        buttonGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGastosActionPerformed(evt);
            }
        });

        buttonContaCorrente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/contaCorrente1.png"))); // NOI18N
        buttonContaCorrente.setToolTipText("Registrar Conta");
        buttonContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContaCorrenteActionPerformed(evt);
            }
        });

        buttonInvestimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/investimento1.png"))); // NOI18N
        buttonInvestimento.setToolTipText("Registrar Investimento");
        buttonInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvestimentoActionPerformed(evt);
            }
        });

        buttonAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/alterarUsuario.png"))); // NOI18N
        buttonAlterarUsuario.setToolTipText("Alterar Usuário");
        buttonAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarUsuarioActionPerformed(evt);
            }
        });

        buttonCartaoCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/cartaoCredito1.png"))); // NOI18N
        buttonCartaoCredito.setToolTipText("Registrar Cartão");
        buttonCartaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCartaoCreditoActionPerformed(evt);
            }
        });

        buttonRenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/renda1.png"))); // NOI18N
        buttonRenda.setToolTipText("Registrar Renda");
        buttonRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRendaActionPerformed(evt);
            }
        });

        tableGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descrição", "Categoria", "Data", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableGastos);

        jLabel2.setText("TABELA GASTOS MÊS CORRENTE");

        buttonGraficoPeriodoTempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/grafico1.png"))); // NOI18N
        buttonGraficoPeriodoTempo.setText("Período Tempo");
        buttonGraficoPeriodoTempo.setPreferredSize(new java.awt.Dimension(190, 73));
        buttonGraficoPeriodoTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGraficoPeriodoTempoActionPerformed(evt);
            }
        });

        buttonGraficoConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/grafico1.png"))); // NOI18N
        buttonGraficoConta.setText("Conta");
        buttonGraficoConta.setPreferredSize(new java.awt.Dimension(190, 29));
        buttonGraficoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGraficoContaActionPerformed(evt);
            }
        });

        buttonGraficoCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/grafico1.png"))); // NOI18N
        buttonGraficoCartao.setText("Cartão");
        buttonGraficoCartao.setPreferredSize(new java.awt.Dimension(190, 29));
        buttonGraficoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGraficoCartaoActionPerformed(evt);
            }
        });

        buttonRelatorioPeriodoTempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/relatorio1.png"))); // NOI18N
        buttonRelatorioPeriodoTempo.setText("Período Tempo");
        buttonRelatorioPeriodoTempo.setPreferredSize(new java.awt.Dimension(190, 73));
        buttonRelatorioPeriodoTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioPeriodoTempoActionPerformed(evt);
            }
        });

        buttonRelatorioConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/relatorio1.png"))); // NOI18N
        buttonRelatorioConta.setText("Conta");
        buttonRelatorioConta.setPreferredSize(new java.awt.Dimension(190, 29));
        buttonRelatorioConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioContaActionPerformed(evt);
            }
        });

        buttonRelatorioCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/relatorio1.png"))); // NOI18N
        buttonRelatorioCartao.setText("Cartão");
        buttonRelatorioCartao.setPreferredSize(new java.awt.Dimension(190, 29));
        buttonRelatorioCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioCartaoActionPerformed(evt);
            }
        });

        jLabel1.setText("GRÁFICO GASTOS POR CATEGORIA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Total dos Gastos"));

        jLabel6.setText("TOTAL GASTOS");

        labelTotalGasto.setText("RESULTADO R$:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalGasto, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelTotalGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo das Contas"));

        jLabel4.setText("SALDO");

        labelSaldoTotal.setText("RESULTADO R$:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(labelSaldoTotal)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelSaldoTotal))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Limite dos Cartões"));

        jLabel8.setText("LIMITE");

        labelTotalLimite.setText("RESULTADO R$:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(labelTotalLimite)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelTotalLimite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonGraficoPeriodoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonRelatorioPeriodoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonGraficoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonRelatorioConta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(102, 102, 102)
                                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonRelatorioCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonGraficoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(71, 71, 71))
        );

        panelPrincipalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonGraficoCartao, buttonGraficoConta, buttonGraficoPeriodoTempo});

        panelPrincipalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonRelatorioCartao, buttonRelatorioConta, buttonRelatorioPeriodoTempo});

        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGraficoPeriodoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGraficoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGraficoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRelatorioPeriodoTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRelatorioConta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRelatorioCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonGraficoCartao, buttonGraficoConta, buttonGraficoPeriodoTempo});

        panelPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonRelatorioCartao, buttonRelatorioConta, buttonRelatorioPeriodoTempo});

        jPanel3.getAccessibleContext().setAccessibleName("Saldo dos Cartões");

        javax.swing.GroupLayout panelBarraLateralLayout = new javax.swing.GroupLayout(panelBarraLateral);
        panelBarraLateral.setLayout(panelBarraLateralLayout);
        panelBarraLateralLayout.setHorizontalGroup(
            panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addGroup(panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttonGastos)
                    .addComponent(buttonContaCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRenda)
                    .addComponent(buttonInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        panelBarraLateralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAlterarUsuario, buttonCartaoCredito, buttonContaCorrente, buttonGastos, buttonInvestimento, buttonRenda});

        panelBarraLateralLayout.setVerticalGroup(
            panelBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLateralLayout.createSequentialGroup()
                .addComponent(buttonGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonContaCorrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCartaoCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInvestimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Registrar");

        registrarGasto_MenuItem.setText("Registrar Gastos");
        registrarGasto_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarGasto_MenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(registrarGasto_MenuItem);

        contaMenuItem.setText("Registrar Conta");
        contaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(contaMenuItem);

        cartaoMenuItem.setText("Registrar Cartao");
        cartaoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(cartaoMenuItem);

        registrarRenda_MenuItem.setText("Registrar Renda");
        registrarRenda_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRenda_MenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(registrarRenda_MenuItem);

        investimentoMenuItem.setText("Registrar Investimento");
        investimentoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investimentoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(investimentoMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Excluir");

        menuItemCartao.setText("Cartão");
        menuItemCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCartaoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCartao);

        menuItemConta.setText("Conta");
        menuItemConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemConta);

        menuItemRenda.setText("Renda");
        menuItemRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRendaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRenda);

        menuItemInvestimento.setText("Investimento");
        menuItemInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvestimentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvestimento);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraLateral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUsuarioCorrente( Usuario usuarioCorrente ) {
        this.usuarioCorrente = usuarioCorrente;
    }
    
    public Usuario getUsuarioCorrente() {
        return this.usuarioCorrente;
    }
    
    
    public void addGrafico(){
         //inserir os dados aqui
        DefaultPieDataset result = new DefaultPieDataset();
//        result.setValue("Linux", 29);
//        result.setValue("Mac", 20);
//        result.setValue("Windows", 51);
//        result.setValue("jhgg", 51);
//        result.setValue("jhgg", 51);
//        result.setValue("Li7777777nux", 29);
     
        result = controlador.dadosGrafico( usuarioCorrente);

        PieChart demo;
        demo = new PieChart("Comparação", "", result); 
        //demo.se
        demo.pack();
        jPanel4.add(demo.getContentPane());
    }
    
    public void addGastosTabela() {
        ArrayList<Gastos> gastos = controlador.buscaGastosMes(usuarioCorrente);
        DefaultTableModel model = (DefaultTableModel) tableGastos.getModel();
        Object[] linha = new Object[5];
        
        for( int i = 0; i < gastos.size(); i++ ) {
            model.setValueAt( gastos.get(i).getDescricao(), i  , 0);
            model.setValueAt( gastos.get(i).getNomeCategoria(), i  , 1);
            
            model.setValueAt( 
                         gastos.get(i).getDataEmissao().getDay() + " / " +
                         gastos.get(i).getDataEmissao().getMonth() + " / " +
                         gastos.get(i).getDataEmissao().getYear(), i  , 2);
            
            model.setValueAt( gastos.get(i).getValor(), i  , 3);
        }
        
        
    }
    
    public void addTotalGastos() {
        labelTotalGasto.setText( "R$ " + Float.toString( usuarioCorrente.getGastoTotal() ) );
    }
    
    public void addTotalSaldo() {
        labelSaldoTotal.setText( "R$ " + Float.toString( usuarioCorrente.getSaldoTotal() ) );
    }
    
    public void addTotalLimite() {
        labelTotalLimite.setText( "R$ " + Float.toString( controlador.buscarLimiteTotalCartao(usuarioCorrente) )  );
    }
    
    public void addInformacoes() {
        controlador.recuperaCategorias();
        addGastosTabela();
        addTotalGastos();
        addTotalSaldo();
        addTotalLimite();
        addGrafico();
        
    }
    
    private void registrarGasto_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarGasto_MenuItemActionPerformed
        IURegistrarGasto registrarGastos =  new IURegistrarGasto(this, true);
        registrarGastos.setLocationRelativeTo(this);
        registrarGastos.setVisible(true);
        
        addGastosTabela();
    }//GEN-LAST:event_registrarGasto_MenuItemActionPerformed

    private void registrarRenda_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRenda_MenuItemActionPerformed
        // TODO add your handling code here:
        IURenda registrarRenda = new IURenda(this,true);
        registrarRenda.setLocationRelativeTo( this );
        registrarRenda.setVisible(true);
    }//GEN-LAST:event_registrarRenda_MenuItemActionPerformed

    private void menuItemCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCartaoActionPerformed
        IUExcluirCartao excluir = new IUExcluirCartao(this, true);
        excluir.setLocationRelativeTo( this );
        excluir.setVisible(true);
    }//GEN-LAST:event_menuItemCartaoActionPerformed

    private void menuItemContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContaActionPerformed
        IUExcluirConta excluir = new IUExcluirConta(this, true);
        excluir.setLocationRelativeTo( this );
        excluir.setVisible(true);
    }//GEN-LAST:event_menuItemContaActionPerformed

    private void menuItemRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRendaActionPerformed
        IUExcluirRenda excluir = new IUExcluirRenda(this, true);
        excluir.setLocationRelativeTo( this );
        excluir.setVisible(true);
    }//GEN-LAST:event_menuItemRendaActionPerformed

    private void buttonRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRendaActionPerformed
        IURenda registrarRenda = new IURenda(this,true);
        registrarRenda.setLocationRelativeTo( this );
        registrarRenda.setVisible(true);
    }//GEN-LAST:event_buttonRendaActionPerformed

    private void buttonCartaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCartaoCreditoActionPerformed
        IUCartao cartao = new IUCartao(this, true);
        cartao.setLocationRelativeTo( this );
        cartao.setVisible(true);
    }//GEN-LAST:event_buttonCartaoCreditoActionPerformed

    private void buttonAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarUsuarioActionPerformed
        IUAlterarUsuario alterar = new IUAlterarUsuario(this, true);
        alterar.setLocationRelativeTo( this );
        alterar.setVisible(true);
    }//GEN-LAST:event_buttonAlterarUsuarioActionPerformed

    private void buttonContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContaCorrenteActionPerformed
        IUConta contaCorrente = new IUConta(this, true);
        contaCorrente.setLocationRelativeTo( this );
        contaCorrente.setVisible(true);
    }//GEN-LAST:event_buttonContaCorrenteActionPerformed

    private void buttonGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGastosActionPerformed
        // TODO add your handling code here:
        IURegistrarGasto registrarGastos =  new IURegistrarGasto(this, true);
        registrarGastos.setLocationRelativeTo(this);
        registrarGastos.setVisible(true);
    }//GEN-LAST:event_buttonGastosActionPerformed

    private void buttonInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvestimentoActionPerformed
        // TODO add your handling code here:
        IUInvestimento investimento = new IUInvestimento(this, true);
        investimento.setLocationRelativeTo(this);
        investimento.setVisible(true);
    }//GEN-LAST:event_buttonInvestimentoActionPerformed

    private void contaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaMenuItemActionPerformed
        IUConta contaCorrente = new IUConta(this, true);
        contaCorrente.setLocationRelativeTo( this );
        contaCorrente.setVisible(true);
    }//GEN-LAST:event_contaMenuItemActionPerformed

    private void cartaoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoMenuItemActionPerformed
        IUCartao cartao = new IUCartao(this, true);
        cartao.setLocationRelativeTo( this );
        cartao.setVisible(true);
    }//GEN-LAST:event_cartaoMenuItemActionPerformed

    private void investimentoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investimentoMenuItemActionPerformed
        IUInvestimento investimento = new IUInvestimento(this, true);
        investimento.setLocationRelativeTo(this);
        investimento.setVisible(true);
    }//GEN-LAST:event_investimentoMenuItemActionPerformed

    private void buttonGraficoPeriodoTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGraficoPeriodoTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGraficoPeriodoTempoActionPerformed

    private void buttonGraficoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGraficoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGraficoContaActionPerformed

    private void buttonGraficoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGraficoCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGraficoCartaoActionPerformed

    private void buttonRelatorioPeriodoTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioPeriodoTempoActionPerformed
        // TODO add your handling code here:
        IURelatorio relatorio = new IURelatorio(this, true);
        relatorio.exibirCampoData();
        relatorio.setTitle("Relatorio de Gastos por Período");
        relatorio.setLocationRelativeTo( this );
        relatorio.setVisible(true);
        
    }//GEN-LAST:event_buttonRelatorioPeriodoTempoActionPerformed

    private void buttonRelatorioContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioContaActionPerformed
        // TODO add your handling code here:
        IURelatorio relatorio = new IURelatorio(this, true);
        relatorio.addTextArea(0);
        relatorio.setTitle("Relatorio de Contas");
        relatorio.setLocationRelativeTo( this );
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonRelatorioContaActionPerformed

    private void buttonRelatorioCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioCartaoActionPerformed
        // TODO add your handling code here:
        
        IURelatorio relatorio = new IURelatorio(this, true);
        relatorio.addTextArea(1);
        relatorio.setTitle("Relatorio de Cartões");
        relatorio.setLocationRelativeTo( this );
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonRelatorioCartaoActionPerformed

    private void menuItemInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvestimentoActionPerformed
        IUExcluirInvestimento excluir = new IUExcluirInvestimento(this, true);
        excluir.setLocationRelativeTo(this);
        excluir.setVisible(true);
    }//GEN-LAST:event_menuItemInvestimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new IUPrincipal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterarUsuario;
    private javax.swing.JButton buttonCartaoCredito;
    private javax.swing.JButton buttonContaCorrente;
    private javax.swing.JButton buttonGastos;
    private javax.swing.JButton buttonGraficoCartao;
    private javax.swing.JButton buttonGraficoConta;
    private javax.swing.JButton buttonGraficoPeriodoTempo;
    private javax.swing.JButton buttonInvestimento;
    private javax.swing.JButton buttonRelatorioCartao;
    private javax.swing.JButton buttonRelatorioConta;
    private javax.swing.JButton buttonRelatorioPeriodoTempo;
    private javax.swing.JButton buttonRenda;
    private javax.swing.JMenuItem cartaoMenuItem;
    private javax.swing.JMenuItem contaMenuItem;
    private javax.swing.JMenuItem investimentoMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelSaldoTotal;
    private javax.swing.JLabel labelTotalGasto;
    private javax.swing.JLabel labelTotalLimite;
    private javax.swing.JMenuItem menuItemCartao;
    private javax.swing.JMenuItem menuItemConta;
    private javax.swing.JMenuItem menuItemInvestimento;
    private javax.swing.JMenuItem menuItemRenda;
    private javax.swing.JPanel panelBarraLateral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JMenuItem registrarGasto_MenuItem;
    private javax.swing.JMenuItem registrarRenda_MenuItem;
    private javax.swing.JTable tableGastos;
    // End of variables declaration//GEN-END:variables
}
